---
- name: Destroy Slurm Cluster Infrastructure
  hosts: localhost
  gather_facts: false
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Get VPC info
      amazon.aws.ec2_vpc_net_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
      register: vpc_info

    - name: Get all instances in VPC
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Project": slurm-cluster
      register: instances
      when: vpc_info.vpcs | length > 0

    - name: Display instances found
      debug:
        msg: "Found {{ instances.instances | length }} instances to terminate"
      when:
        - vpc_info.vpcs | length > 0
        - instances.instances is defined

    - name: Build instance ID list
      set_fact:
        instance_ids: "{{ instances.instances | map(attribute='instance_id') | list }}"
      when:
        - vpc_info.vpcs | length > 0
        - instances.instances is defined
        - instances.instances | length > 0

    - name: Terminate all instances
      amazon.aws.ec2_instance:
        instance_ids: "{{ instance_ids }}"
        region: "{{ aws_region }}"
        state: terminated
        wait: true
      when:
        - vpc_info.vpcs | length > 0
        - instances.instances is defined
        - instances.instances | length > 0
      register: terminate_result

    - name: Wait for instances to fully terminate
      pause:
        seconds: 45
      when:
        - vpc_info.vpcs | length > 0
        - instances.instances is defined
        - instances.instances | length > 0

    - name: Delete security group
      amazon.aws.ec2_security_group:
        name: "{{ vpc_name }}-sg"
        region: "{{ aws_region }}"
        state: absent
      when: vpc_info.vpcs | length > 0
      register: sg_delete
      until: sg_delete is not failed
      retries: 5
      delay: 10
      ignore_errors: true

    - name: Get subnet info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: subnet_info
      when: vpc_info.vpcs | length > 0

    - name: Delete subnets
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        cidr: "{{ item.cidr_block }}"
        region: "{{ aws_region }}"
        state: absent
      loop: "{{ subnet_info.subnets }}"
      when:
        - vpc_info.vpcs | length > 0
        - subnet_info.subnets is defined
      register: subnet_delete
      until: subnet_delete is not failed
      retries: 5
      delay: 10
      ignore_errors: true

    - name: Get route table info
      amazon.aws.ec2_vpc_route_table_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: route_table_info
      when: vpc_info.vpcs | length > 0

    - name: Delete route tables
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        route_table_id: "{{ item.id }}"
        region: "{{ aws_region }}"
        lookup: id
        state: absent
      loop: "{{ route_table_info.route_tables }}"
      when:
        - vpc_info.vpcs | length > 0
        - route_table_info.route_tables is defined
        - not item.associations[0].main | default(false)
      ignore_errors: true

    - name: Get network interface info
      amazon.aws.ec2_eni_info:
        region: "{{ aws_region }}"
        filters:
          vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: eni_info
      when: vpc_info.vpcs | length > 0

    - name: Get Elastic IP info
      amazon.aws.ec2_eip_info:
        region: "{{ aws_region }}"
      register: eip_info
      when: vpc_info.vpcs | length > 0

    - name: Filter EIPs associated with our VPC
      set_fact:
        vpc_eips: "{{ eip_info.addresses | selectattr('network_interface_id', 'defined') | selectattr('network_interface_id', 'in', eni_info.network_interfaces | map(attribute='id') | list) | list }}"
      when:
        - vpc_info.vpcs | length > 0
        - eip_info.addresses is defined
        - eni_info.network_interfaces is defined

    - name: Disassociate Elastic IPs
      amazon.aws.ec2_eip:
        region: "{{ aws_region }}"
        public_ip: "{{ item.public_ip }}"
        state: absent
        release_on_disassociation: true
      loop: "{{ vpc_eips | default([]) }}"
      when:
        - vpc_info.vpcs | length > 0
        - vpc_eips is defined
        - vpc_eips | length > 0
      ignore_errors: true

    - name: Wait for EIPs to release
      pause:
        seconds: 10
      when:
        - vpc_info.vpcs | length > 0
        - vpc_eips is defined
        - vpc_eips | length > 0

    - name: Get IGW info
      amazon.aws.ec2_vpc_igw_info:
        region: "{{ aws_region }}"
        filters:
          attachment.vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
      register: igw_info
      when: vpc_info.vpcs | length > 0

    - name: Delete Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
        region: "{{ aws_region }}"
        state: absent
      when:
        - vpc_info.vpcs | length > 0
        - igw_info.internet_gateways is defined
        - igw_info.internet_gateways | length > 0
      register: igw_delete
      until: igw_delete is not failed
      retries: 10
      delay: 15
      ignore_errors: true

    - name: Delete VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        state: absent
      when: vpc_info.vpcs | length > 0
      register: vpc_delete
      until: vpc_delete is not failed
      retries: 5
      delay: 10
      ignore_errors: true

    - name: Remove inventory file
      file:
        path: ./inventory/hosts
        state: absent

    - name: Verify no instances remain
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Project": slurm-cluster
          instance-state-name: [pending, running, stopping, stopped]
      register: remaining_instances

    - name: Display remaining instances warning
      debug:
        msg: "WARNING: {{ remaining_instances.instances | length }} instances still exist!"
      when: remaining_instances.instances | length > 0

    - name: Display completion message
      debug:
        msg:
          - "Slurm cluster infrastructure destroyed!"
          - "Instances terminated: {{ instances.instances | length | default(0) }}"
          - "Remaining instances: {{ remaining_instances.instances | length }}"
          - "VPC deleted: {{ vpc_info.vpcs | length > 0 }}"
